### API Requests 



### Get Temperature by cep - W O R K I N G
GET https://server-image-233313523725.us-central1.run.app/temp/11075301 HTTP/1.1


### Get Temperature by cep - Not Found CEP
GET https://server-image-233313523725.us-central1.run.app/temp/33333333 HTTP/1.1


### Get Temperature by cep - Malformed CEP (not enough digits)
GET https://server-image-233313523725.us-central1.run.app/temp/3213 HTTP/1.1


### Get Temperature by cep - Malformed CEP (too many digits)
GET https://server-image-233313523725.us-central1.run.app/temp/3212222222223 HTTP/1.1


### Get Temperature by cep - Malformed CEP (not a number)
GET https://server-image-233313523725.us-central1.run.app/temp/3212a3 HTTP/1.1